[package]
name = "utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.13.2", default-features = false }

[features]
default = [ "2d" ]
2d = [
    "bevy/bevy_render",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_sprite",
    "bevy/bevy_winit",
]
